export const catalog: { symbol: string; name: string; type: 'stock' | 'crypto' }[] = [
  { symbol: 'NVDA', type: 'stock', name: 'NVIDIA Corporation' },
  { symbol: 'GOOGL', type: 'stock', name: 'Alphabet Inc.' },
  { symbol: 'GOOG', type: 'stock', name: 'Alphabet Inc.' },
  { symbol: 'AAPL', type: 'stock', name: 'Apple Inc.' },
  { symbol: 'MSFT', type: 'stock', name: 'Microsoft Corporation' },
  { symbol: 'AMZN', type: 'stock', name: 'Amazon.com, Inc.' },
  { symbol: 'AVGO', type: 'stock', name: 'Broadcom Inc.' },
  { symbol: 'TSLA', type: 'stock', name: 'Tesla, Inc.' },
  { symbol: 'META', type: 'stock', name: 'Meta Platforms, Inc.' },
  { symbol: 'WMT', type: 'stock', name: 'Walmart Inc.' },
  { symbol: 'MU', type: 'stock', name: 'Micron Technology, Inc.' },
  { symbol: 'AMD', type: 'stock', name: 'Advanced Micro Devices, Inc.' },
  { symbol: 'INTC', type: 'stock', name: 'Intel Corporation' },
  { symbol: 'ASML', type: 'stock', name: 'ASML Holding N.V.' },
  { symbol: 'COST', type: 'stock', name: 'Costco Wholesale Corporation' },
  { symbol: 'CSCO', type: 'stock', name: 'Cisco Systems, Inc.' },
  { symbol: 'NFLX', type: 'stock', name: 'Netflix, Inc.' },
  { symbol: 'LRCX', type: 'stock', name: 'Lam Research Corporation' },
  { symbol: 'AMAT', type: 'stock', name: 'Applied Materials, Inc.' },
  { symbol: 'PLTR', type: 'stock', name: 'Palantir Technologies Inc.' },
  { symbol: 'TXN', type: 'stock', name: 'Texas Instruments Incorporated' },
  { symbol: 'KLAC', type: 'stock', name: 'KLA Corporation' },
  { symbol: 'LIN', type: 'stock', name: 'Linde plc' },
  { symbol: 'QCOM', type: 'stock', name: 'QUALCOMM Incorporated' },
  { symbol: 'ARM', type: 'stock', name: 'Arm Holdings plc' },
  { symbol: 'TMUS', type: 'stock', name: 'T-Mobile US, Inc.' },
  { symbol: 'PEP', type: 'stock', name: 'PepsiCo, Inc.' },
  { symbol: 'ADI', type: 'stock', name: 'Analog Devices, Inc.' },
  { symbol: 'AMGN', type: 'stock', name: 'Amgen Inc.' },
  { symbol: 'STX', type: 'stock', name: 'Seagate Technology Holdings plc' },
  { symbol: 'PANW', type: 'stock', name: 'Palo Alto Networks, Inc.' },
  { symbol: 'WDC', type: 'stock', name: 'Western Digital Corporation' },
  { symbol: 'GILD', type: 'stock', name: 'Gilead Sciences, Inc.' },
  { symbol: 'APP', type: 'stock', name: 'AppLovin Corporation' },
  { symbol: 'ISRG', type: 'stock', name: 'Intuitive Surgical, Inc.' },
  { symbol: 'MRVL', type: 'stock', name: 'Marvell Technology, Inc.' },
  { symbol: 'CRWD', type: 'stock', name: 'CrowdStrike Holdings, Inc.' },
  { symbol: 'HON', type: 'stock', name: 'Honeywell International Inc.' },
  { symbol: 'PDD', type: 'stock', name: 'PDD Holdings Inc.' },
  { symbol: 'SHOP', type: 'stock', name: 'Shopify Inc.' },
  { symbol: 'BKNG', type: 'stock', name: 'Booking Holdings Inc.' },
  { symbol: 'SBUX', type: 'stock', name: 'Starbucks Corporation' },
  { symbol: 'VRTX', type: 'stock', name: 'Vertex Pharmaceuticals Incorporated' },
  { symbol: 'INTU', type: 'stock', name: 'Intuit Inc.' },
  { symbol: 'CEG', type: 'stock', name: 'Constellation Energy Corporation' },
  { symbol: 'CDNS', type: 'stock', name: 'Cadence Design Systems, Inc.' },
  { symbol: 'SNPS', type: 'stock', name: 'Synopsys, Inc.' },
  { symbol: 'ADBE', type: 'stock', name: 'Adobe Inc.' },
  { symbol: 'MAR', type: 'stock', name: 'Marriott International, Inc.' },
  { symbol: 'CMCSA', type: 'stock', name: 'Comcast Corporation' },
  { symbol: 'ADP', type: 'stock', name: 'Automatic Data Processing, Inc.' },
  { symbol: 'MNST', type: 'stock', name: 'Monster Beverage Corporation' },
  { symbol: 'FTNT', type: 'stock', name: 'Fortinet, Inc.' },
  { symbol: 'CSX', type: 'stock', name: 'CSX Corporation' },
  { symbol: 'ABNB', type: 'stock', name: 'Airbnb, Inc.' },
  { symbol: 'MELI', type: 'stock', name: 'MercadoLibre, Inc.' },
  { symbol: 'MDLZ', type: 'stock', name: 'Mondelez International, Inc.' },
  { symbol: 'MPWR', type: 'stock', name: 'Monolithic Power Systems, Inc.' },
  { symbol: 'ORLY', type: 'stock', name: "O'Reilly Automotive, Inc." },
  { symbol: 'NXPI', type: 'stock', name: 'NXP Semiconductors N.V.' },
  { symbol: 'REGN', type: 'stock', name: 'Regeneron Pharmaceuticals, Inc.' },
  { symbol: 'AEP', type: 'stock', name: 'American Electric Power Company, Inc.' },
  { symbol: 'DDOG', type: 'stock', name: 'Datadog, Inc.' },
  { symbol: 'ROST', type: 'stock', name: 'Ross Stores, Inc.' },
  { symbol: 'WBD', type: 'stock', name: 'Warner Bros. Discovery, Inc.' },
  { symbol: 'DASH', type: 'stock', name: 'DoorDash, Inc.' },
  { symbol: 'CTAS', type: 'stock', name: 'Cintas Corporation' },
  { symbol: 'BKR', type: 'stock', name: 'Baker Hughes Company' },
  { symbol: 'MSTR', type: 'stock', name: 'Strategy Inc' },
  { symbol: 'PCAR', type: 'stock', name: 'PACCAR Inc' },
  { symbol: 'FANG', type: 'stock', name: 'Diamondback Energy, Inc.' },
  { symbol: 'MCHP', type: 'stock', name: 'Microchip Technology Incorporated' },
  { symbol: 'EA', type: 'stock', name: 'Electronic Arts Inc.' },
  { symbol: 'XEL', type: 'stock', name: 'Xcel Energy Inc.' },
  { symbol: 'FAST', type: 'stock', name: 'Fastenal Company' },
  { symbol: 'ADSK', type: 'stock', name: 'Autodesk, Inc.' },
  { symbol: 'FER', type: 'stock', name: 'Ferrovial N.V.' },
  { symbol: 'EXC', type: 'stock', name: 'Exelon Corporation' },
  { symbol: 'IDXX', type: 'stock', name: 'IDEXX Laboratories, Inc.' },
  { symbol: 'TTWO', type: 'stock', name: 'Take-Two Interactive Software, Inc.' },
  { symbol: 'CCEP', type: 'stock', name: 'Coca-Cola Europacific Partners PLC' },
  { symbol: 'PYPL', type: 'stock', name: 'PayPal Holdings, Inc.' },
  { symbol: 'ODFL', type: 'stock', name: 'Old Dominion Freight Line, Inc.' },
  { symbol: 'KDP', type: 'stock', name: 'Keurig Dr Pepper Inc.' },
  { symbol: 'ALNY', type: 'stock', name: 'Alnylam Pharmaceuticals, Inc.' },
  { symbol: 'TRI', type: 'stock', name: 'Thomson Reuters Corporation' },
  { symbol: 'PAYX', type: 'stock', name: 'Paychex, Inc.' },
  { symbol: 'ROP', type: 'stock', name: 'Roper Technologies, Inc.' },
  { symbol: 'CPRT', type: 'stock', name: 'Copart, Inc.' },
  { symbol: 'AXON', type: 'stock', name: 'Axon Enterprise, Inc.' },
  { symbol: 'WDAY', type: 'stock', name: 'Workday, Inc.' },
  { symbol: 'GEHC', type: 'stock', name: 'GE HealthCare Technologies Inc.' },
  { symbol: 'KHC', type: 'stock', name: 'The Kraft Heinz Company' },
  { symbol: 'INSM', type: 'stock', name: 'Insmed Incorporated' },
  { symbol: 'DXCM', type: 'stock', name: 'DexCom, Inc.' },
  { symbol: 'ZS', type: 'stock', name: 'Zscaler, Inc.' },
  { symbol: 'CTSH', type: 'stock', name: 'Cognizant Technology Solutions Corporation' },
  { symbol: 'VRSK', type: 'stock', name: 'Verisk Analytics, Inc.' },
  { symbol: 'TEAM', type: 'stock', name: 'Atlassian Corporation' },
  { symbol: 'CHTR', type: 'stock', name: 'Charter Communications, Inc.' },
  { symbol: 'CSGP', type: 'stock', name: 'CoStar Group, Inc.' },
  { symbol: 'BTC', type: 'crypto', name: 'Bitcoin' },
  { symbol: 'ETH', type: 'crypto', name: 'Ethereum' },
  { symbol: 'SOL', type: 'crypto', name: 'Solana' },
  { symbol: 'BNB', type: 'crypto', name: 'BNB' },
  { symbol: 'XRP', type: 'crypto', name: 'XRP' },
  { symbol: 'ADA', type: 'crypto', name: 'Cardano' },
];
